// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4atcEHhDSejGOlnuQB8eI-JHhnmRbQvs',
    appId: '1:474179370524:web:b7795f3151adeef56069d9',
    messagingSenderId: '474179370524',
    projectId: 'reddit-d896c',
    authDomain: 'reddit-d896c.firebaseapp.com',
    storageBucket: 'reddit-d896c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDLeTAvCb6UJW7MYc1TH_KhNt3cetIns',
    appId: '1:474179370524:android:fda691b6ebe3dc786069d9',
    messagingSenderId: '474179370524',
    projectId: 'reddit-d896c',
    storageBucket: 'reddit-d896c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaPBIxq9uHdkgczTy5Di-DVA8lK82lxmU',
    appId: '1:474179370524:ios:9d103c0aa9ae9cdc6069d9',
    messagingSenderId: '474179370524',
    projectId: 'reddit-d896c',
    storageBucket: 'reddit-d896c.appspot.com',
    iosClientId: '474179370524-t5v21927jh4gsgfc5at03jmemd5k7ddu.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaPBIxq9uHdkgczTy5Di-DVA8lK82lxmU',
    appId: '1:474179370524:ios:9d254f89fb4149e86069d9',
    messagingSenderId: '474179370524',
    projectId: 'reddit-d896c',
    storageBucket: 'reddit-d896c.appspot.com',
    iosClientId: '474179370524-nbotgsk9k76tjvpnddipr9mej7s78rqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
